// 英语单词词汇表
const vocabularyList = [
  // 已替换图片的单词
  { chinese:"企鹅", english:"Penguin", phonetic:"/ˈpeŋ.ɡwɪn/", category:"animal" },
  { chinese:"狮子", english:"Lion", phonetic:"/ˈlaɪ.ən/", category:"animal" },
  { chinese:"蔬菜", english:"Vegetable", phonetic:"/ˈvedʒ.tə.bəl/", category:"food" },
  { chinese:"鲸鱼", english:"Whale", phonetic:"/weɪl/", category:"animal" },
  { chinese:"猴子", english:"Monkey", phonetic:"/ˈmʌŋ.ki/", category:"animal" },
  { chinese:"兔子", english:"Rabbit", phonetic:"/ˈræb.ɪt/", category:"animal" },
  { chinese:"狐狸", english:"Fox", phonetic:"/fɒks/", category:"animal" },
  { chinese:"冰淇淋", english:"Ice Cream", phonetic:"/ˌaɪs ˈkriːm/", category:"food" },
  { chinese:"苹果", english:"Apple", phonetic:"/ˈæp.əl/", category:"fruit" },
  { chinese:"钥匙", english:"Key", phonetic:"/kiː/", category:"daily" },
  { chinese:"斑马", english:"Zebra", phonetic:"/ˈzeb.rə/", category:"animal" },
  { chinese:"大象", english:"Elephant", phonetic:"/ˈel.ɪ.fənt/", category:"animal" },
  { chinese:"面条", english:"Noodle", phonetic:"/ˈnuː.dl/", category:"food" },
  { chinese:"雨伞", english:"Umbrella", phonetic:"/ʌmˈbrel.ə/", category:"daily" },
  { chinese:"果汁", english:"Juice", phonetic:"/dʒuːs/", category:"food" },
  { chinese:"铅笔", english:"Pencil", phonetic:"/ˈpen.səl/", category:"daily" },
  { chinese:"橘子", english:"Orange", phonetic:"/ˈɒr.ɪndʒ/", category:"fruit" },
  { chinese:"礼物", english:"Gift", phonetic:"/ɡɪft/", category:"daily" },
  { chinese:"香蕉", english:"Banana", phonetic:"/bəˈnɑː.nə/", category:"fruit" },
  { chinese:"太阳", english:"Sun", phonetic:"/sʌn/", category:"daily" },
  
  // 新增适合幼儿的单词
  // 动物类
  { chinese:"鸟", english:"Bird", phonetic:"/bɜːd/", category:"animal" },
  { chinese:"鱼", english:"Fish", phonetic:"/fɪʃ/", category:"animal" },
  { chinese:"青蛙", english:"Frog", phonetic:"/frɒɡ/", category:"animal" },
  { chinese:"蝴蝶", english:"Butterfly", phonetic:"/ˈbʌtəflaɪ/", category:"animal" },
  { chinese:"蜜蜂", english:"Bee", phonetic:"/biː/", category:"animal" },
  { chinese:"蚂蚁", english:"Ant", phonetic:"/ænt/", category:"animal" },
  { chinese:"蜗牛", english:"Snail", phonetic:"/sneɪl/", category:"animal" },
  { chinese:"乌龟", english:"Turtle", phonetic:"/ˈtɜːtl/", category:"animal" },
  { chinese:"仓鼠", english:"Hamster", phonetic:"/ˈhæmstər/", category:"animal" },
  { chinese:"豚鼠", english:"Guinea Pig", phonetic:"/ˈɡɪni pɪɡ/", category:"animal" },
  { chinese:"老鼠", english:"Mouse", phonetic:"/maʊs/", category:"animal" },
  { chinese:"奶牛", english:"Cow", phonetic:"/kaʊ/", category:"animal" },
  { chinese:"马", english:"Horse", phonetic:"/hɔːs/", category:"animal" },
  { chinese:"羊", english:"Sheep", phonetic:"/ʃiːp/", category:"animal" },
  { chinese:"猪", english:"Pig", phonetic:"/pɪɡ/", category:"animal" },
  { chinese:"鸡", english:"Chicken", phonetic:"/ˈtʃɪkɪn/", category:"animal" },
  { chinese:"鸭", english:"Duck", phonetic:"/dʌk/", category:"animal" },
  { chinese:"鹅", english:"Goose", phonetic:"/ɡuːs/", category:"animal" },
  { chinese:"鸽子", english:"Pigeon", phonetic:"/ˈpɪdʒɪn/", category:"animal" },
  
  // 食物类
  { chinese:"面包", english:"Bread", phonetic:"/bred/", category:"food" },
  { chinese:"牛奶", english:"Milk", phonetic:"/mɪlk/", category:"food" },
  { chinese:"鸡蛋", english:"Egg", phonetic:"/eɡ/", category:"food" },
  { chinese:"米饭", english:"Rice", phonetic:"/raɪs/", category:"food" },
  { chinese:"蛋糕", english:"Cake", phonetic:"/keɪk/", category:"food" },
  { chinese:"饼干", english:"Cookie", phonetic:"/ˈkʊki/", category:"food" },
  { chinese:"糖果", english:"Candy", phonetic:"/ˈkændi/", category:"food" },
  { chinese:"巧克力", english:"Chocolate", phonetic:"/ˈtʃɒklət/", category:"food" },
  { chinese:"奶酪", english:"Cheese", phonetic:"/tʃiːz/", category:"food" },
  { chinese:"水果", english:"Fruit", phonetic:"/fruːt/", category:"food" },
  { chinese:"肉", english:"Meat", phonetic:"/miːt/", category:"food" },
  { chinese:"汉堡", english:"Hamburger", phonetic:"/ˈhæmbɜːɡə/", category:"food" },
  { chinese:"披萨", english:"Pizza", phonetic:"/ˈpiːtsə/", category:"food" },
  { chinese:"水", english:"Water", phonetic:"/ˈwɔːtə/", category:"food" },
  { chinese:"茶", english:"Tea", phonetic:"/tiː/", category:"food" },
  
  // 日常用品类
  { chinese:"杯子", english:"Cup", phonetic:"/kʌp/", category:"daily" },
  { chinese:"碗", english:"Bowl", phonetic:"/bəʊl/", category:"daily" },
  { chinese:"盘子", english:"Plate", phonetic:"/pleɪt/", category:"daily" },
  { chinese:"勺子", english:"Spoon", phonetic:"/spuːn/", category:"daily" },
  { chinese:"叉子", english:"Fork", phonetic:"/fɔːk/", category:"daily" },
  { chinese:"刀子", english:"Knife", phonetic:"/naɪf/", category:"daily" },
  { chinese:"毛巾", english:"Towel", phonetic:"/ˈtaʊəl/", category:"daily" },
  { chinese:"牙刷", english:"Toothbrush", phonetic:"/ˈtuːθbrʌʃ/", category:"daily" },
  { chinese:"牙膏", english:"Toothpaste", phonetic:"/ˈtuːθpeɪst/", category:"daily" },
  { chinese:"肥皂", english:"Soap", phonetic:"/səʊp/", category:"daily" },
  { chinese:"洗发水", english:"Shampoo", phonetic:"/ʃæmˈpuː/", category:"daily" },
  { chinese:"梳子", english:"Comb", phonetic:"/kəʊm/", category:"daily" },
  { chinese:"镜子", english:"Mirror", phonetic:"/ˈmɪrə/", category:"daily" },
  { chinese:"衣服", english:"Clothes", phonetic:"/kləʊðz/", category:"daily" },
  { chinese:"鞋子", english:"Shoes", phonetic:"/ʃuːz/", category:"daily" },
  { chinese:"帽子", english:"Hat", phonetic:"/hæt/", category:"daily" },
  { chinese:"袜子", english:"Socks", phonetic:"/sɒks/", category:"daily" },
  { chinese:"手套", english:"Gloves", phonetic:"/ɡlʌvz/", category:"daily" },
  { chinese:"围巾", english:"Scarf", phonetic:"/skɑːf/", category:"daily" },
  { chinese:"花", english:"Flower", phonetic:"/ˈflaʊ.ər/", category:"daily" },
  { chinese:"房子", english:"House", phonetic:"/haʊs/", category:"daily" },
  { chinese:"树", english:"Tree", phonetic:"/triː/", category:"daily" },
  { chinese:"书", english:"Book", phonetic:"/bʊk/", category:"daily" },
  { chinese:"学校", english:"School", phonetic:"/skuːl/", category:"daily" },
  { chinese:"老师", english:"Teacher", phonetic:"/ˈtiː.tʃər/", category:"daily" },
  
  // 颜色类
  { chinese:"红色", english:"Red", phonetic:"/red/", category:"color" },
  { chinese:"蓝色", english:"Blue", phonetic:"/bluː/", category:"color" },
  { chinese:"黄色", english:"Yellow", phonetic:"/ˈjeləʊ/", category:"color" },
  { chinese:"绿色", english:"Green", phonetic:"/ɡriːn/", category:"color" },
  { chinese:"紫色", english:"Purple", phonetic:"/ˈpɜːpl/", category:"color" },
  { chinese:"橙色", english:"Orange", phonetic:"/ˈɒrɪndʒ/", category:"color" },
  { chinese:"粉色", english:"Pink", phonetic:"/pɪŋk/", category:"color" },
  { chinese:"黑色", english:"Black", phonetic:"/blæk/", category:"color" },
  { chinese:"白色", english:"White", phonetic:"/waɪt/", category:"color" },
  { chinese:"灰色", english:"Gray", phonetic:"/ɡreɪ/", category:"color" },
  
  // 数字类
  { chinese:"一", english:"One", phonetic:"/wʌn/", category:"number" },
  { chinese:"二", english:"Two", phonetic:"/tuː/", category:"number" },
  { chinese:"三", english:"Three", phonetic:"/θriː/", category:"number" },
  { chinese:"四", english:"Four", phonetic:"/fɔː/", category:"number" },
  { chinese:"五", english:"Five", phonetic:"/faɪv/", category:"number" },
  { chinese:"六", english:"Six", phonetic:"/sɪks/", category:"number" },
  { chinese:"七", english:"Seven", phonetic:"/ˈsevn/", category:"number" },
  { chinese:"八", english:"Eight", phonetic:"/eɪt/", category:"number" },
  { chinese:"九", english:"Nine", phonetic:"/naɪn/", category:"number" },
  { chinese:"十", english:"Ten", phonetic:"/ten/", category:"number" },
  
  // 水果类
  { chinese:"葡萄", english:"Grape", phonetic:"/ɡreɪp/", category:"fruit" },
  { chinese:"草莓", english:"Strawberry", phonetic:"/ˈstrɔːbəri/", category:"fruit" },
  { chinese:"西瓜", english:"Watermelon", phonetic:"/ˈwɔːtəmelən/", category:"fruit" },
  { chinese:"桃子", english:"Peach", phonetic:"/piːtʃ/", category:"fruit" },
  { chinese:"梨", english:"Pear", phonetic:"/peə/", category:"fruit" },
  { chinese:"菠萝", english:"Pineapple", phonetic:"/ˈpaɪnæpl/", category:"fruit" },
  { chinese:"猕猴桃", english:"Kiwi", phonetic:"/ˈkiːwi/", category:"fruit" },
  
  // 交通工具类
  { chinese:"汽车", english:"Car", phonetic:"/kɑː/", category:"transport" },
  { chinese:"公交车", english:"Bus", phonetic:"/bʌs/", category:"transport" },
  { chinese:"出租车", english:"Taxi", phonetic:"/ˈtæksi/", category:"transport" },
  { chinese:"自行车", english:"Bicycle", phonetic:"/ˈbaɪsɪkl/", category:"transport" },
  { chinese:"摩托车", english:"Motorcycle", phonetic:"/ˈməʊtəsaɪkl/", category:"transport" },
  { chinese:"火车", english:"Train", phonetic:"/treɪn/", category:"transport" },
  { chinese:"飞机", english:"Airplane", phonetic:"/ˈeəpleɪn/", category:"transport" },
  { chinese:"船", english:"Ship", phonetic:"/ʃɪp/", category:"transport" },
  { chinese:"小船", english:"Boat", phonetic:"/bəʊt/", category:"transport" },
  { chinese:"直升机", english:"Helicopter", phonetic:"/ˈhelɪkɒptə/", category:"transport" },
  
  // 身体部位类
  { chinese:"头", english:"Head", phonetic:"/hed/", category:"body" },
  { chinese:"眼睛", english:"Eye", phonetic:"/aɪ/", category:"body" },
  { chinese:"鼻子", english:"Nose", phonetic:"/nəʊz/", category:"body" },
  { chinese:"嘴", english:"Mouth", phonetic:"/maʊθ/", category:"body" },
  { chinese:"耳朵", english:"Ear", phonetic:"/ɪə/", category:"body" },
  { chinese:"脸", english:"Face", phonetic:"/feɪs/", category:"body" },
  { chinese:"手", english:"Hand", phonetic:"/hænd/", category:"body" },
  { chinese:"手指", english:"Finger", phonetic:"/ˈfɪŋɡə/", category:"body" },
  { chinese:"脚", english:"Foot", phonetic:"/fʊt/", category:"body" },
  { chinese:"腿", english:"Leg", phonetic:"/leɡ/", category:"body" },
  
  // 未提供新链接的单词
  { chinese:"猫", english:"Cat", phonetic:"/kæt/", category:"animal" },
  { chinese:"狗", english:"Dog", phonetic:"/dɒɡ/", category:"animal" },
  
  // 亲属类
  { chinese:"爸爸", english:"Father", phonetic:"/ˈfɑːðər/", category:"family" },
  { chinese:"妈妈", english:"Mother", phonetic:"/ˈmʌðər/", category:"family" },
  { chinese:"兄弟", english:"Brother", phonetic:"/ˈbrʌðər/", category:"family" },
  { chinese:"姐妹", english:"Sister", phonetic:"/ˈsɪstər/", category:"family" },
  { chinese:"祖父", english:"Grandfather", phonetic:"/ˈɡrænfɑːðər/", category:"family" },
  { chinese:"祖母", english:"Grandmother", phonetic:"/ˈɡrænmʌðər/", category:"family" },
  { chinese:"儿子", english:"Son", phonetic:"/sʌn/", category:"family" },
  { chinese:"女儿", english:"Daughter", phonetic:"/ˈdɔːtər/", category:"family" },
  { chinese:"叔叔", english:"Uncle", phonetic:"/ˈʌŋkl/", category:"family" },
  { chinese:"阿姨", english:"Aunt", phonetic:"/ænt/", category:"family" },
  { chinese:"堂兄弟", english:"Cousin", phonetic:"/ˈkʌzn/", category:"family" },
  { chinese:"丈夫", english:"Husband", phonetic:"/ˈhʌzbənd/", category:"family" },
  { chinese:"妻子", english:"Wife", phonetic:"/waɪf/", category:"family" }
];

window.vocabularyList = vocabularyList;